In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mlss-sp-25/sample_submission.csv
/kaggle/input/mlss-sp-25/train.csv
/kaggle/input/mlss-sp-25/test.csv

In [2]:
train = pd.read_csv('/kaggle/input/mlss-sp-25/train.csv')
test = pd.read_csv('/kaggle/input/mlss-sp-25/test.csv')
sample_submission = pd.read_csv('/kaggle/input/mlss-sp-25/sample_submission.csv')
object_id = test['object_id']

In [3]:
train

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,object_id,transaction_currency,height_cm,width_cm,location,category,date,n_previous_owners,creation_year,is_titled,signed,dated,n_exhibited,artist_birth_year,artist_death_year,estimate,price_realized
0,yzkxu,USD,67.3,55.9,New York,Paintings,2008-01-11,4.0,1996.0,NaN,True,True,0,1937.0,NaN,15000.00,9375.000
1,iponc,USD,122.2,122.2,New York,Paintings,2008-01-11,1.0,NaN,False,True,True,0,1952.0,NaN,2500.00,3750.000
2,ybhua,USD,15.2,10.2,New York,Paintings,2008-01-11,2.0,NaN,True,True,True,2,1958.0,NaN,6000.00,11250.000
3,koiua,USD,58.4,67.3,New York,Paintings,2008-01-11,2.0,NaN,False,True,True,0,1973.0,NaN,5000.00,9375.000
4,wynxu,USD,68.6,52.7,New York,Paintings,2008-01-11,1.0,1957.0,NaN,True,False,0,1917.0,NaN,25000.00,15000.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105896,sznqd,EUR,83.3,65.4,Paris,Paintings,2016-09-14,1.0,NaN,NaN,False,False,5,1864.0,1956.0,19724.25,30995.250
105897,ykbkf,EUR,14.9,26.8,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1816.0,1878.0,5635.50,5353.725
105898,yqcfd,EUR,22.1,17,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1851.0,1929.0,1127.10,1127.100
105899,amurb,EUR,49.9,70.9,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1624.0,1685.0,14088.75,14088.750
105900,uckrb,EUR,18.5,16,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,NaN,NaN,28177.50,26768.625

In [4]:
test

/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,object_id,transaction_currency,height_cm,width_cm,location,category,date,n_previous_owners,creation_year,is_titled,signed,dated,n_exhibited,artist_birth_year,artist_death_year,estimate
0,gnite,EUR,9.9,32.4,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1814.0,1883.0,676.26
1,agxtc,EUR,97,146.7,Paris,Paintings,2016-09-14,3.0,NaN,NaN,False,False,1,1754.0,1837.0,16906.50
2,otrwd,EUR,24.7,20,Paris,Paintings,2016-09-14,1.0,NaN,NaN,False,False,0,1755.0,1812.0,16906.50
3,yqyhe,EUR,31.2,24.2,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,0,1799.0,1826.0,9580.35
4,cpqne,EUR,16.5,24.8,Paris,Paintings,2016-09-14,NaN,NaN,NaN,False,False,1,1789.0,1822.0,4508.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52946,yhuiq,USD,33,22.9,New York,Drawings & Watercolors,2025-01-23,1.0,1915.0,NaN,True,True,1,1873.0,1948.0,6000.00
52947,kwujo,USD,36.8,52.1,New York,Drawings & Watercolors,2025-01-23,1.0,NaN,NaN,False,False,0,1856.0,1925.0,300000.00
52948,wyapo,USD,21,30.5,New York,Drawings & Watercolors,2025-01-23,1.0,1879.0,NaN,False,False,0,1836.0,1910.0,40000.00
52949,ebiyn,USD,11.4,19.7,New York,Drawings & Watercolors,2025-01-23,1.0,1890.0,NaN,True,True,0,1830.0,1902.0,12500.00
52950,sogyn,USD,9.5,16.5,New York,Drawings & Watercolors,2025-01-23,1.0,1890.0,NaN,True,True,0,1830.0,1902.0,7000.00

In [5]:
col =['height_cm','width_cm', 'location','transaction_currency','category','creation_year','is_titled', 'signed', 'dated','n_exhibited', 'artist_birth_year', 'estimate']
train = train[col + ['price_realized']] 
test = test[col]

In [6]:
train.isnull().sum()

height_cm               21700
width_cm                21700
location                 1879
transaction_currency        0
category                    0
creation_year           75552
is_titled               88123
signed                      0
dated                       0
n_exhibited                 0
artist_birth_year       16253
estimate                   84
price_realized              0
dtype: int64

In [7]:
test.isnull().sum()

height_cm                4173
width_cm                 4173
location                    0
transaction_currency        0
category                    0
creation_year           27382
is_titled               40819
signed                      0
dated                       0
n_exhibited                 0
artist_birth_year        4967
estimate                   82
dtype: int64

In [8]:
drop_col = ['creation_year','is_titled']
train = train.drop(drop_col, axis = 1)
test = test.drop(drop_col, axis = 1)

In [9]:
def clean_numeric(value):
    try:
        return float(value)
    except:
        return None

train = train.copy()
test = test.copy()

train.loc[:, 'height_cm'] = train['height_cm'].apply(clean_numeric)
train.loc[:, 'width_cm'] = train['width_cm'].apply(clean_numeric)
test.loc[:, 'height_cm'] = test['height_cm'].apply(clean_numeric)
test.loc[:, 'width_cm'] = test['width_cm'].apply(clean_numeric)

In [10]:
mode_imputatipn_col = ['location', 'artist_birth_year']
from sklearn.impute import SimpleImputer
mode_imputer = SimpleImputer(strategy = 'most_frequent')
train[mode_imputatipn_col] = mode_imputer.fit_transform(train[mode_imputatipn_col])
test[mode_imputatipn_col] = mode_imputer.transform(test[mode_imputatipn_col])

In [11]:
median_imputatipn_col = ['estimate', 'height_cm', 'width_cm']
from sklearn.impute import SimpleImputer
median_imputer = SimpleImputer(strategy = 'median')
train[median_imputatipn_col] = median_imputer.fit_transform(train[median_imputatipn_col])
test[median_imputatipn_col] = median_imputer.transform(test[median_imputatipn_col])

In [12]:
train['area'] = train['height_cm'] * train['width_cm']
test['area'] = test['height_cm'] * test['width_cm']
drop_col = ['height_cm','width_cm']
train = train.drop(drop_col, axis = 1)
test = test.drop(drop_col, axis = 1)

In [13]:
"""train['area'].mean()"""

"train['area'].mean()"

In [14]:
"""train['area'] = np.log(train['area'])
test['area'] = np.log(test['area'])"""

"train['area'] = np.log(train['area'])\ntest['area'] = np.log(test['area'])"

In [15]:
#train['area'].mean()

In [16]:
train.isnull().sum()

location                0
transaction_currency    0
category                0
signed                  0
dated                   0
n_exhibited             0
artist_birth_year       0
estimate                0
price_realized          0
area                    0
dtype: int64

In [17]:
test.isnull().sum()

location                0
transaction_currency    0
category                0
signed                  0
dated                   0
n_exhibited             0
artist_birth_year       0
estimate                0
area                    0
dtype: int64

In [18]:
from datetime import datetime
current_year = datetime.now().year
train['aprox_age_painting'] = ((current_year - train['artist_birth_year'])/10).astype(int)*10
test['aprox_age_painting'] = ((current_year - test['artist_birth_year'])/10).astype(int)*10
train = train.drop('artist_birth_year', axis = 1)
test = test.drop('artist_birth_year', axis = 1)

In [19]:
train

,location,transaction_currency,category,signed,dated,n_exhibited,estimate,price_realized,area,aprox_age_painting
0,New York,USD,Paintings,True,True,0,15000.00,9375.000,3762.07,80
1,New York,USD,Paintings,True,True,0,2500.00,3750.000,14932.84,70
2,New York,USD,Paintings,True,True,2,6000.00,11250.000,155.04,60
3,New York,USD,Paintings,True,True,0,5000.00,9375.000,3930.32,50
4,New York,USD,Paintings,True,False,0,25000.00,15000.000,3615.22,100
...,...,...,...,...,...,...,...,...,...,...
105896,Paris,EUR,Paintings,False,False,5,19724.25,30995.250,5447.82,160
105897,Paris,EUR,Paintings,False,False,0,5635.50,5353.725,399.32,200
105898,Paris,EUR,Paintings,False,False,0,1127.10,1127.100,375.70,170
105899,Paris,EUR,Paintings,False,False,0,14088.75,14088.750,3537.91,400
105900,Paris,EUR,Paintings,False,False,0,28177.50,26768.625,296.00,90

In [20]:
test

,location,transaction_currency,category,signed,dated,n_exhibited,estimate,area,aprox_age_painting
0,Paris,EUR,Paintings,False,False,0,676.26,320.76,210
1,Paris,EUR,Paintings,False,False,1,16906.50,14229.90,270
2,Paris,EUR,Paintings,False,False,0,16906.50,494.00,270
3,Paris,EUR,Paintings,False,False,0,9580.35,755.04,220
4,Paris,EUR,Paintings,False,False,1,4508.40,409.20,230
...,...,...,...,...,...,...,...,...,...
52946,New York,USD,Drawings & Watercolors,True,True,1,6000.00,755.70,150
52947,New York,USD,Drawings & Watercolors,False,False,0,300000.00,1917.28,160
52948,New York,USD,Drawings & Watercolors,False,False,0,40000.00,640.50,180
52949,New York,USD,Drawings & Watercolors,True,True,0,12500.00,224.58,190
52950,New York,USD,Drawings & Watercolors,True,True,0,7000.00,156.75,190

In [21]:
catagorical_cols = ['category', 'signed', 'dated', 'location', 'transaction_currency']
#catagorical_cols = ['category', 'signed', 'dated', 'n_exhibited', 'aprox_age_painting']
train_dummies = pd.get_dummies(train[catagorical_cols], drop_first = True).astype(int)
test_dummies = pd.get_dummies(test[catagorical_cols], drop_first = True).astype(int)

In [22]:
test_dummies = test_dummies.reindex(columns = train_dummies.columns, fill_value = 0)

In [23]:
test_dummies

,signed,dated,category_Paintings,location_Dubai,location_Geneva,location_Hong Kong,location_London,location_Mumbai,location_New York,location_Paris,location_Shanghai,location_Zürich,transaction_currency_CNY,transaction_currency_EUR,transaction_currency_GBP,transaction_currency_HKD,transaction_currency_INR,transaction_currency_USD
0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
4,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52946,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
52947,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
52948,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
52949,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
52950,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1

In [24]:
train

,location,transaction_currency,category,signed,dated,n_exhibited,estimate,price_realized,area,aprox_age_painting
0,New York,USD,Paintings,True,True,0,15000.00,9375.000,3762.07,80
1,New York,USD,Paintings,True,True,0,2500.00,3750.000,14932.84,70
2,New York,USD,Paintings,True,True,2,6000.00,11250.000,155.04,60
3,New York,USD,Paintings,True,True,0,5000.00,9375.000,3930.32,50
4,New York,USD,Paintings,True,False,0,25000.00,15000.000,3615.22,100
...,...,...,...,...,...,...,...,...,...,...
105896,Paris,EUR,Paintings,False,False,5,19724.25,30995.250,5447.82,160
105897,Paris,EUR,Paintings,False,False,0,5635.50,5353.725,399.32,200
105898,Paris,EUR,Paintings,False,False,0,1127.10,1127.100,375.70,170
105899,Paris,EUR,Paintings,False,False,0,14088.75,14088.750,3537.91,400
105900,Paris,EUR,Paintings,False,False,0,28177.50,26768.625,296.00,90

In [25]:
train = pd.concat([train.drop(catagorical_cols, axis = 1), train_dummies], axis = 1)
test = pd.concat([test.drop(catagorical_cols, axis = 1), test_dummies], axis = 1)

In [26]:
train

,n_exhibited,estimate,price_realized,area,aprox_age_painting,signed,dated,category_Paintings,location_Dubai,location_Geneva,...,location_New York,location_Paris,location_Shanghai,location_Zürich,transaction_currency_CNY,transaction_currency_EUR,transaction_currency_GBP,transaction_currency_HKD,transaction_currency_INR,transaction_currency_USD
0,0,15000.00,9375.000,3762.07,80,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
1,0,2500.00,3750.000,14932.84,70,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
2,2,6000.00,11250.000,155.04,60,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
3,0,5000.00,9375.000,3930.32,50,1,1,1,0,0,...,1,0,0,0,0,0,0,0,0,1
4,0,25000.00,15000.000,3615.22,100,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105896,5,19724.25,30995.250,5447.82,160,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
105897,0,5635.50,5353.725,399.32,200,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
105898,0,1127.10,1127.100,375.70,170,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
105899,0,14088.75,14088.750,3537.91,400,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0
105900,0,28177.50,26768.625,296.00,90,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,0

In [27]:
from sklearn.linear_model import LinearRegression
X_train = train.drop('price_realized', axis = 1)
y_train = train['price_realized']
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

LinearRegression()

In [28]:
pred = lr_model.predict(test)

In [29]:
sample_submission

      object_id  price_realized
0         gnite      67887.1425
1         agxtc       3655.0700
2         otrwd      43267.3000
3         yqyhe      39582.9200
4         cpqne       2750.6000
...         ...             ...
52946     yhuiq      35266.0000
52947     kwujo     166352.0000
52948     wyapo      43737.1000
52949     ebiyn       8948.5000
52950     sogyn      19669.4310

[52951 rows x 2 columns]

In [30]:
submission = pd.DataFrame()
submission['object_id'] = object_id
submission['price_realized1'] = pred
submission

      object_id  price_realized1
0         gnite     16649.379477
1         agxtc     85818.495642
2         otrwd     36874.463979
3         yqyhe     27251.561450
4         cpqne     70494.419520
...         ...              ...
52946     yhuiq     83589.544969
52947     kwujo    354857.823704
52948     wyapo     51992.529353
52949     ebiyn     43089.320263
52950     sogyn     36673.443265

[52951 rows x 2 columns]

In [31]:
submission.to_csv('submission.csv', index = False)

In [32]:
import pandas as pd
import numpy as np

def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

actuals = sample_submission
submission = submission

df = submission.merge(actuals, on="object_id")

mape = mean_absolute_percentage_error(df["price_realized"], df["price_realized1"])
print(f"MAPE: {mape:.2f}%")

MAPE: 2756.42%

In [33]:
import statsmodels.api as sm
# Add constant term for intercept
X_train = sm.add_constant(X_train)
test = sm.add_constant(test)

# Fit the linear regression model
model = sm.OLS(y_train, X_train).fit()

# Predict on the test set
predictions = model.predict(test)

# Display summary of model
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         price_realized   R-squared:                       0.536
Model:                            OLS   Adj. R-squared:                  0.536
Method:                 Least Squares   F-statistic:                     6803.
Date:                Tue, 18 Feb 2025   Prob (F-statistic):               0.00
Time:                        03:00:31   Log-Likelihood:            -1.6194e+06
No. Observations:              105901   AIC:                         3.239e+06
Df Residuals:                  105882   BIC:                         3.239e+06
Df Model:                          18
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                    -2.631e+04   2.83e+04     -0.930      0.352   -8.18e+04    2.91e+04
n_exhibited               4.894e+04   2715.246     18.026      0.000    4.36e+04    5.43e+04
estimate                     1.1665      0.004    325.093      0.000       1.159       1.174
area                     -1.242e-06   1.64e-05     -0.076      0.940   -3.34e-05    3.09e-05
aprox_age_painting          21.5356     35.642      0.604      0.546     -48.323      91.394
signed                   -2.067e+04   8933.426     -2.313      0.021   -3.82e+04   -3156.435
dated                     4.363e+04   7905.969      5.518      0.000    2.81e+04    5.91e+04
category_Paintings        2.815e+04   7907.214      3.560      0.000    1.26e+04    4.36e+04
location_Dubai           -9929.4059   1.15e+05     -0.086      0.931   -2.36e+05    2.16e+05
location_Geneva          -3.059e+04   3.89e+04     -0.786      0.432   -1.07e+05    4.56e+04
location_Hong Kong        2.692e+04   1.41e+04      1.911      0.056    -688.778    5.45e+04
location_London           -393.2705   2.78e+04     -0.014      0.989    -5.5e+04    5.42e+04
location_Mumbai           2.463e+04    3.7e+04      0.665      0.506   -4.79e+04    9.72e+04
location_New York         2.274e+04   1.12e+05      0.203      0.839   -1.97e+05    2.42e+05
location_Paris            2.193e+04   1.68e+04      1.306      0.192    -1.1e+04    5.48e+04
location_Shanghai        -1.387e+04   4.16e+04     -0.334      0.739   -9.54e+04    6.76e+04
location_Zürich          -3.507e+04   1.26e+05     -0.278      0.781   -2.83e+05    2.13e+05
transaction_currency_CNY -1.387e+04   4.16e+04     -0.334      0.739   -9.54e+04    6.76e+04
transaction_currency_EUR -1.242e+04   2.72e+04     -0.457      0.647   -6.56e+04    4.08e+04
transaction_currency_GBP  9063.1128   3.31e+04      0.274      0.784   -5.57e+04    7.39e+04
transaction_currency_HKD  2.692e+04   1.41e+04      1.911      0.056    -688.778    5.45e+04
transaction_currency_INR  2.463e+04    3.7e+04      0.665      0.506   -4.79e+04    9.72e+04
transaction_currency_USD  5026.1621   9.84e+04      0.051      0.959   -1.88e+05    1.98e+05
==============================================================================
Omnibus:                   366098.182   Durbin-Watson:                   1.976
Prob(Omnibus):                  0.000   Jarque-Bera (JB):     162218810253.995
Skew:                          65.613   Prob(JB):                         0.00
Kurtosis:                    6064.840   Cond. No.                     6.70e+24
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.29e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.